name: Insight
version: 1.3
main: cc.akashic.insight.Insight
api-version: '1.16'
authors: [ Myth ]
description: A Paper plugin to display Minecraft event text in console.
website: mc.akashic.cc
softdepend: [ spark ]


commands:
  disableend:
    description: Command of Insight Disable End.
    usage: |
      /<command>
    permission: insight.disableend

  enableend:
    description: Command of Insight Enable End.
    usage: |
      /<command>
    permission: insight.enableend

  players:
    description: Command of Insight Players.
    usage: |
      /<command>
    permission: insight.players

permissions:
  insight.disableend:
    description: Allows command of Insight Disable End.
    default: op
  insight.enableend:
    description: Allows command of Insight Enable End.
    default: op
  insight.players:
    description: Allows command of Insight Players.
    default: op