name: Insight
version: 1.0
main: cc.akashic.insight.Insight
api-version: 1.18
authors: [ Myth ]
description: A Spigot plugin to display Minecraft event text in console.
website: mc.akashic.cc


commands:
  insight:
    description: Commands of Insight.
    usage: |
      /<command> stat playoneminute
      /<command> stat deaths
      /<command> stat mobkills
    permission: insight.insight

  xray:
    description: Command of Insight Xray.
    usage: |
      /<command> <player> inventory
      /<command> <player> enderchest
      /<command> <player> hand
    permission: insight.xray

  shareitems:
    description: Command of Insight ShareItems.
    usage: |
      /<command>
      /<command> hand
    permission: insight.shareitems


permissions:
  insight.insight:
    description: Allows commands of Insight.
    default: op
  insight.xray:
    description: Allows commands of Xray.
    default: op
  insight.shareitems:
    description: Allows commands of ShareItems.
    default: true
