name: Insight
version: 1.2
main: cc.akashic.insight.Insight
api-version: 1.18
authors: [ Myth ]
description: A Spigot plugin to display Minecraft event text in console.
website: mc.akashic.cc
softdepend: [ spark ]


commands:
  insight:
    description: Commands of Insight.
    usage: |
      /<command> reload
      /<command> stat playoneminute
      /<command> stat deaths
      /<command> stat mobkills
      /<command> stat pickupdiamond
      /<command> stat minenetherrack
      /<command> stat minedeepslate
      /<command> stat mineancientdebris
    permission: insight.insight

  xray:
    description: Command of Insight Xray.
    usage: |
      /<command> <player> inventory
      /<command> <player> enderchest
      /<command> <player> hand
    permission: insight.xray

  shareitems:
    description: Command of Insight ShareItems.
    usage: |
      /<command>
      /<command> hand
    permission: insight.shareitems

  tpskeep:
    description: Command of Insight TPSKeep.
    usage: |
      /<command> true
      /<command> false
    permission: insight.tpskeep

  slogan:
    description: Command of Insight Slogan.
    usage: |
      /<command> set <slogan>
      /<command> clear
    permission: insight.slogan

  leader:
    description: Command of Insight Leader Board.
    usage: |
      /<command> leader
    permission: insight.leader

  keepspectator:
    description: Command of Insight Spectator Keeper.
    usage: |
      /<command> on
      /<command> off
    permission: insight.keepspectator


permissions:
  insight.insight:
    description: Allows commands of Insight.
    default: op
  insight.xray:
    description: Allows commands of Xray.
    default: op
  insight.shareitems:
    description: Allows commands of ShareItems.
    default: true
  insight.tpskeep:
    description: Allows commands of TPSKeep.
    default: op
  insight.slogan:
    description: Allows commands of Slogan.
    default: true
  insight.slogan.clearothers:
    description: Allows commands of Slogan clear <player>.
    default: op
  insight.slogan.reload:
    description: Allows commands of Slogan reload.
    default: op
  insight.slogan.save:
    description: Allows commands of Slogan save.
    default: op
  insight.leader:
    description: Allows commands of Leader Board.
    default: true
  insight.keepspectator:
    description: Allows command of Insight Spectator Keeper.
    default: op